version: '3.1'
 
services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: rasa run --enable-api --cors "*"
 
  actions:
    image: rasa/rasa-sdk:3.5.0
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: python -m rasa_sdk --debug
